---
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.84 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
    volumes:
      - /path/to/config:/config # optional
      - /path/to/assets:/assets # optional
    ports:
      - 192.168.1.12:50005:3000  # optional, destination should match ${WEB_APP_PORT} variable above.
      - 192.168.1.12:69:69/udp
      - 192.168.1.12:50085:80  # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
